### ISSUE TITLE
Error when starting panel selection

### ISSUE THREAD

**Issue by CmdrJk** [hawkeye-stan/msfs-popout-panel-manager#1]
When starting the panel selection process I get an Microsoft.Net Error message "Parameter is not valid" This never happened before in any older version of the tool

![Desktop Screenshot 2021 12 07 - 16 52 29 48](https://user-images.githubusercontent.com/70865232/145062105-e74bc85e-20d0-4359-ad7e-bdeacdc864e3.png)

**Comment by ssewell** [comment]
@CmdrJk Could you copy and paste the full body of the exception and call stack (the text shown the bottom of that dialog)?

**Comment by hawkeye-stan** [comment]
The full exception message detail will be very helpful. I can then nail down the code and data argument where the exception occurs. Thanks.
