### ISSUE TITLE
MSFS 1.34.16.0 & POPM 4.0.3 - Can't Pop Out Panels on Asobo C172R

### ISSUE THREAD

**Issue by CablingOptional** [hawkeye-stan/msfs-popout-panel-manager#101]
I'm just trying this tool for the first time, so apologies if I've missed an easy step.
I'm flying the Asobo C172R, and trying to pop out the main 6-pack panel, and I got the error show below:
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/29014806/863c0f7f-bfb3-475d-8850-992954ea202f)

Any idea what the fix for this is?

I'm using MSFS 1.34.16.0 & POPM 4.0.3

Thanks

**Comment by CablingOptional** [comment]
Update: I tried to pop out one of the Garmin GPS panels (the GNS 430) and it worked perfectly...seems the issue is just with the panels related to the various analog gauges.

**Comment by hawkeye-stan** [comment]
Unfortunately analog gauges cannot be popped out which is a limitation in MSFS. Only glass screen can be popped out.
