### ISSUE TITLE
Loading custom camera Failed

### ISSUE THREAD

**Issue by Psychokiller1888** [hawkeye-stan/msfs-popout-panel-manager#102]
Hi!

Trying to auto pop out my A320N fly pad. So I followed your guide, with one pop out only.

When setting the panel, I zoom out slightly, then place the cursor on that said panel

When I try to start POPM, it fails at loading the custom camera. I've red that one should try to ALT+0 to confirm it loads the custom camera view, and it does. Still, POPM executes camera reset just fine, but fails at loading the custom camera before poping out the panel

**Comment by Psychokiller1888** [comment]
If I try to help it and manually do ALT+0 when it is trying to load it, it passes it, but then fails to pop out the screen, although the placement of the marker is ok. Popping out the EFB manually works though, but it's not touch functional unfortunately.

**Comment by hawkeye-stan** [comment]
Can you see if Alt-0 setup in MSFS keyboard binding is the keyboard zero above the alpha keys and not the zero in number pad?

**Comment by Psychokiller1888** [comment]
I'm using the numeric keys above the alpha keys, not the numpad

**Comment by Psychokiller1888** [comment]
CH keyboard, set as QWERTZ

**Comment by hawkeye-stan** [comment]
For failing to pop out for you manually help to adjust custom camera view, please make sure you've Right-Alt Left-click setup in MSFS control settings ("New UI Window" for keyboard) to pop out panel. But for failure to load custom camera before pop out with ALT-0 (it has to be LEFT-ALT in MSFS control keyboard setup), I'm at a lost of what could be causing your issue since you can manually load the custom camera by pressing the keystroke on your keyboard.

**Comment by Psychokiller1888** [comment]
I guess you are from the US right? You guys have Right-Alt, the rest of the world has Alt-Gr

Yet, I just confirmed that when pressing ALT-GR, MSFS detects it as Right Alt

https://laurent.s-ul.eu/GCizpIxN

And also the use of LEFT-ALT for custom cameras, as I'm using them quite often for different quick view (EFB, looking at you, I want you poped out and touch able....)

https://laurent.s-ul.eu/EmaUokvF

**Comment by Psychokiller1888** [comment]
Ok, I'm out of here, thank you for trying, but this simply doesn't work

Fresh OS install (new motherboard, CPU, ram), fresh MSFS install, GSX, FBW A32n, FSHUD, simbrief, Flow pro, and button skipper

Resetting camera works, then everything fails as before

https://laurent.s-ul.eu/jQ0S9jqw
