### ISSUE TITLE
h145 PMS50 GTN 750 bug / Realsimgear 750 touch screen

### ISSUE THREAD

**Issue by sonnynr9** [hawkeye-stan/msfs-popout-panel-manager#104]
I have a problem where all the buttons work in the beginning. After some pressing around to make a FPL and in and out of the PROC page i cant click MAP in the top left corner of the 750 in main menu.
I discovered that pretty much the whole left side of buttons are intermittently not working and mid and right side of the realsimgear 750 touch screen is working all the time i press.

I have tried alot of settings and calibrations but nothing seems to fix it. I have noticed that when i touch the left side of the screen, i can sometimes see the circle that it makes when the finger touches the screen, the circle is above my finger so it doesnt press the actual area of intended.

Any fixes here?

https://www.youtube.com/watch?v=6B3ozVwogWY

Chris

**Comment by hawkeye-stan** [comment]
Hi Chris,

Sorry for the delay reply, I was out of town for the past couple weeks. Anyway, if you're using RealSimGear , can you disable touch capability for your selected panel in POPM? Change it so the hand icon is not "green" (means disable). See screenshot below. If I can recall correctly, RealSimGear has it's own mouse/touch emulation and conflicts with POPM touch feature. I've other users who encountered similar issues with either newer or older version of RealSimGear panel. 

<img width="743" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/9e379241-0710-4c83-8b54-da5434dd8a6e">

The little circle you saw near your finger when you touch the screen is probably RealSimGear showing where your finger is at and activates touch emulation. Unfortunately, I don't have RealSimGear to test with so I'm not sure why half your GTN750 is working well and the other half is not.

**Comment by sonnynr9** [comment]
God morning,

To disable the hand button did not do it. If I click the screen it shows the greyish circle and the respective button, say "Flight Plan", it get marked as light blue color but it doesn't get pressed.

If I manually press right alt and hover the mouse over the aircraft's built in 750, it gets to work correctly.

Now (haven't done anything really except for disabling and enabling the hand icon to green for some reason it works better but now the top bar works intermittently. The frequencies button at the top works but you have to first press it and get it marked then press it again to interact as a mouse click.

I will continue fiddle around with it and see what I come up with.

Kind regards
Christian

Skickat från Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Stanley ***@***.***>
Skickat: Wednesday, January 17, 2024 10:04:47 PM
Till: hawkeye-stan/msfs-popout-panel-manager ***@***.***>
Kopia: sonnynr9 ***@***.***>; Author ***@***.***>
Ämne: Re: [hawkeye-stan/msfs-popout-panel-manager] h145 PMS50 GTN 750 bug / Realsimgear 750 touch screen (Issue #104)


Hi Chris,

Sorry for the delay reply, I was out of town for the past couple weeks. Anyway, if you're using RealSimGear , can you disable touch capability for your selected panel in POPM? Change it so the hand icon is not "green" (means disable). See screenshot below. If I can recall correctly, RealSimGear has it's own mouse/touch emulation and conflicts with POPM touch feature. I've other users who encountered similar issues with either newer or older version of RealSimGear panel.

image.png (view on web)<https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/9e379241-0710-4c83-8b54-da5434dd8a6e>

The little circle you saw near your finger when you touch the screen is probably RealSimGear showing where your finger is at and activates touch emulation. Unfortunately, I don't have RealSimGear to test with so I'm not sure why half your GTN750 is working well and the other half is not.
