### ISSUE TITLE
Feature- Close all pop outs

### ISSUE THREAD

**Issue by rob2791** [hawkeye-stan/msfs-popout-panel-manager#108]
I'd like to request a feature, a button that closes all pop outs. This would be especially useful when "Hide Title Bar" is used.

**Comment by hawkeye-stan** [comment]
Button added and implemented and will be included in the next release. Currently, I'm still working on some other major features and will release all at the same time.

Stanley

<img width="749" alt="image" src="https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/1ca1ee0b-fa94-4ff5-a585-f5fe04facfdc">

**Comment by rob2791** [comment]
That looks great!
You have no idea how helpful this will be. 
I’ll mark this as closed.
