### ISSUE TITLE
Panels unable to stick to monitor that is specified in profile

### ISSUE THREAD

**Issue by hawkeye-stan** [hawkeye-stan/msfs-popout-panel-manager#11]
User reported issue: 

[MovedSmile53222](https://forums.flightsimulator.com/u/MovedSmile53222)
[2h](https://forums.flightsimulator.com/t/updated-with-new-features-msfs-pop-out-panel-manager-v3-2-beta-automatically-pop-out-and-save-panel-position/460613/136?u=roastgnu)
Thanks for this tool. It seems very useful but I cannot make it work.
I have a 3 monitors set-up:
1 A 1920x1200 Main monitor where MSFS pop-up panel manager is displayed
2 My MSFS 4K TV
3 A 1920x1080 touch screen where the pop-out panels should be displayed.

I use it with A320NX FBW
I do the panel selection for the 4 main panels (starting with ND then PFD and both EICAS)
I press Start Pop-out.
Panels are extracted and they are displayed on my Main monitor.
I position them on my Touch screen.
I press File/Restart
I press Start Pop Out again.
Panels are extracted on the main monitor. I can see them briefly on the Touch screen but 3 of them return to the Main monitor. Only one stay on the Touch screen. It is not always the same.
Panel Location parameters ( X-Pos, Y-Pos, Width or Height) are correct.
If I retype one of these parameters, the panel goes at the right place on the Touch screen.

I try also with both G1000 on C172. Same thing. One panel stays on the Touch screen, the other return to the Main monitor.
The Error log seems OK.
I have one of these lines everytime I open the tool:
2022-02-11 14:00:42,280 [1] INFO MSFSPopoutPanelManager.WpfApp.App - DPI Awareness is set to: Process_Per_Monitor_DPI_Aware
I also have this line the first time I use the tool:
2022-02-10 11:56:45,725 [1] ERROR MSFSPopoutPanelManager.WpfApp.App - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
It didn’t come back.

Thanks for your help.

Yves

**Comment by YLevesque34** [comment]
Hi Stanley

Thanks for fast response.
Here are 3 screen captures of the G1000 (easier to shaw than the A3NX FBW)
1 Location and setting.png shows the parameters for 2 G1000 panels
2  Multiscreen View.png shows all 3 monitors after pressing Start Pop out . The Main monitor on the left, part of the 4k MSFS on top right and the Touch screen on bottom right. We can see Panel2 on the Touch screen and Panel1 that has returned to the Main monitor.
3 Multiscreen View after editing Width.png. If I manually retype 740 for Panel1  Width in Panel Location and Settings, Panel1 return to the Touch screen at the right place.

Let me know if you need more information

Yves
![G1000 Location and Settings](https://user-images.githubusercontent.com/99516144/153687960-8d488a7b-e357-41af-a1f0-2244b1fada04.png)

![Multiscreen View](https://user-images.githubusercontent.com/99516144/153688164-f693b382-788d-4b9d-8540-a6561347e7eb.png)

![Multiscreen View after editing Width](https://user-images.githubusercontent.com/99516144/153688247-54d40c2f-8613-4b4e-b7d8-3de31b6154c8.png)

**Comment by hawkeye-stan** [comment]
Thanks for the screenshots. The PFD and MFD coordinates looked good. And I was assuming the PFD panel never got restored but that's not true since it was not at its default upper left coordinate of X=0, Y=0. My app's code has it popped out in the upper left corner before finally moving the panel to its saved location. In your screenshot, the PFD panel definitely got moved off from the upper left corner of your main monitor. 

Your case is weird and I'm baffled why it only works only on the first panel and not the other ones. I'll start my investigation and will try to replicate your situation.

**Comment by YLevesque34** [comment]
I found the problem.
It is caused by Sizer 4.0 that I used previously to position the panels.
If I close Sizer then everything works fine. If I reopen Sizer, the problem come back.
This is something that you should document.
Thanks for looking at it.
Keep on your good work!
Yves

**Comment by hawkeye-stan** [comment]
I'm glad that you've found the cause of the issue. I will add to documentation about the potential conflicts with other window placement apps.
