### ISSUE TITLE
GeForce overlays behave erratically when POPM in use.

### ISSUE THREAD

**Issue by SoapyGit** [hawkeye-stan/msfs-popout-panel-manager#110]
I am using two 7" ELECROW touch screens to mimic the touch controllers in the Vision Jet on a PC. When I switch the GeForce overlay (Alt+F3) on to adjust the filters, the game filter overlay on the main screen contracts to the size of my 7" monitor and I cannot get the mouse to move outside the 7" contstraint in the main screen  ( whilst the rest of the main screen remains as normal.  At the same time the mouse arrow appears on BOTH  7" monitors as well as the in the constrained area of the main Samsung 1440 Ultrawide. I have 4 screens; the three above and and a Dell 1920x1080 which I use for Discord and LNM all being driven by a 3060ti and 5600X

When I first switch on the GeForce Experience overlay on (3060ti) the overlay bounces around between the two touch screens  and the main screen and doesn't settle unless I  disconnect the two 7" screens.  I haven't a clue how to proceed and I've spent days trying to diagnose the problem.  Any help would be greatly appreciated (and probably maintain my sanity 🤪

**Comment by hawkeye-stan** [comment]
This may be a MSFS/Nvidia issue since POPM does not control the size of panel when GeForce Experience filter is activated. The Nvidia overlay has all kinds of problem with pop out from frame generation, FPS loss, DX11/DX12 compatibility and crashes, etc. And I personally stopped using filter since I can't get it to play nice with pop out panels.

**Comment by SoapyGit** [comment]
> This may be a MSFS/Nvidia issue..

Thanks for the helfpul response; at least I know I'm not losing it !

  I use the filter overlay to adjust screen display. So I guess I'll have to adjust if need be before popping out.  Thank you for the excellent POPM and your selfless support.
