### ISSUE TITLE
Pop Out Panel Manager does not automatically switch to the aicraft profile

### ISSUE THREAD

**Issue by SMN204** [hawkeye-stan/msfs-popout-panel-manager#114]
Pop Out Panel Manager does not automatically switch to the profile of the running aicraft in the game.
I select the profile manually...

Or for each airplane I have to mark it here as "active" and change it for another airplane?
And that profile will be always selected for any airplane ?
![Auto Pop Out inactive](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/60313040/196df245-1ff3-48eb-910e-bce4393ba874)

**Comment by hawkeye-stan** [comment]
Yes. You've to mark the profile to an airplane. All livery for that aircraft will then also bind to the aircraft.
