### ISSUE TITLE
Windows 11

### ISSUE THREAD

**Issue by Obbiwan22** [hawkeye-stan/msfs-popout-panel-manager#118]
Hello everyone
until now I was using POPM and MSFS2020 on a Windows 10 PC without any problems.
I just upgraded to a more powerful machine running Windows 11 and since then I haven't been able to get POPM to work.
at first everything is fine and as soon as I have to capture the image from the G1000 (this is an example) it's impossible, I get an error.
I have read and tried a number of solutions without success to date.
I'm starting to wonder if there isn't a problem with Windows 11
Do you have a lead?
Thank you all

**Comment by hawkeye-stan** [comment]
Would you please let me know what do you mean by capture image from G1000? POPM does not have capture image function. By off chance, if POPM does not work on your new PC, do you have visual C++ runtime, which is required by MSFS SimConnect to function which many 3rd party MSFS apps/plugins rely on, including POPM. On some new PC, visual C++ runtime does not get install automatically. 

You can download the runtime here:
https://aka.ms/vs/17/release/vc_redist.x64.exe

You can also flightsim.to POPM page and look for "How to install" and see if you're missing any steps.
https://flightsim.to/file/35759/msfs-pop-out-panel-manager

**Comment by Obbiwan22** [comment]
hello thank you for answering me,
actually it is not a screenshot as such but rather the floating window which is not displayed.
I put the x64 runtime back on and I took the time to re-read the page to find out how to install POPM, I took the opportunity to check in the MSFS2020 devmode if there was a simConnect connection to POPM and that's it. is indeed the case.
despite all this does not work, I can clearly see the green circle which is displayed when POPM is executed, but after 3 seconds nothing and then I get the Failed message
thanks again for your assistance

**Comment by hawkeye-stan** [comment]
This probably means either the default MSFS pop out key binding (Left-Alt Right-click) was not bound to activate pop out or something in your system is blocking POPM from executing keyboard command. Try running POPM as administrator.

**Comment by Obbiwan22** [comment]
hello, I found the solution and it's thanks to you, but not the one you thought. I tested in administrator mode and using the Left-Alt Right-click keys without success.
So I went through the preferences menu again and at the very bottom I saw "Use Left Control + Right control to Pop Out Panel", so I tried and BINGO it works even without administrator mode :D
Thanks again for taking some of your time
