### ISSUE TITLE
Resizing pop-out panel w/ touch

### ISSUE THREAD

**Issue by kirkroyster** [hawkeye-stan/msfs-popout-panel-manager#119]
I began having inconsistent touch issues with the PMS50 GTN750 panel in various aircraft, seemingly after I changed the width and height of the popped out panel.  I could touch the COM standby button and it would respond 1-2 times, but would freeze thereafter and not respond.  Similar with a few other buttons on the panel.

So I deleted the panel, recreated it and did not change the size, and all buttons are fully reliable.

Have you observed issues after resizing the GTN750 popped out panel?  I'm using the latest version, 2.2.30, and your software version 4.1.0.0004.

Windows 11, MSFS 2020 SU15, 1.37.18.0.

Any guidance or considerations when I desire to resize panels would be appreciated.

**Comment by kirkroyster** [comment]
Update - I do not believe this issue has anything to do with resizing.  I have reproduced it on the unchanged panels for the GTN750.  I have tried multiple monitors, so I have probably eliminated the monitor as the issue.  I always see the circle gesture when touching the monitor, and the GTN750 buttons always do something, such as highlighting, when I touch them.

The pattern generally is when performing the same process multiple times.  But there are instances when this is not the case.

Any general ideas on troubleshooting this issue, appreciated.  I did play with the timer value, but these are displays connected directly to the conmputer (usb-c and hdmi).

**Comment by hawkeye-stan** [comment]
I'm looking into the issue but wasn't able to reproduce on both of my touch monitors. Adjusting the touch time delay value within POPM probably is not your issue since you're getting touch response but it starts behaving erratically after a few times. I'll continue to look into my POPM code and do more debugging to see if something else is hanging the touch detection process in your case. 

When POPM does not response to touch, would you please check task manager and see if POPM is usage high CPU cycle? If it is, it means POPM mostly likely have gone into a loop to detect touch. POPM should use a max of 3% to 5% CPU cycle and should be idle at 0% most of the time.

**Comment by kirkroyster** [comment]
Please note that when this occurs, there are other fields that I am able to touch and get a response.  So the whole thing is not frozen.  I can reproduce this at will so I will report back soon with what POPM is doing in task manager.

**Comment by kirkroyster** [comment]
Ok, some additional information that may help.  When it is non responsive, there is no CPU activity for POPM.  But what I think I have identified, is that if I move my mouse, this clears the issue and I can touch the field and get a response.  There are some times when the mouse suddenly moves over from the touch monitor to the main monitor within the MSFS application which I have in windowed mode.  Have you noticed this behavior of MSFS "claiming the mouse pointer" over into the main window?  I wonder if this could be related to the issue.  What would cause MSFS to pull the mouse pointer over into the MSFS application window when the only thing I'm doing is touching the COM1 frequency in the popped out panel?

**Comment by hawkeye-stan** [comment]
The behavior for MSFS claiming the mouse pointer is an important POPM feature to enable refocus of MSFS game window after you touch application or screen outside of MSFS main game window. This feature is to overcome a long existing bug in the game when you touch/mouse click another app/window on desktop, MSFS flight controls (joysticks, throttle) will lose all control until you manually click the game window again. You can turn this off if you choose to for each POPM assigned panel by unchecking "Auto Game Refocus" setting.
