### ISSUE TITLE
Auto Start option doesn't work with Steam version of MSFS

### ISSUE THREAD

**Issue by hellobody** [hawkeye-stan/msfs-popout-panel-manager#120]
Unable to turn on Auto Start option in preferences:
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/1161879/6d7bcceb-32d4-4208-b27a-e12786b55014)

The problem is inside AppAutoStart class GetFilePath method:
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/1161879/1c66c859-21c1-4709-99ed-f58343028196)

Looks like there is no LocalCache folder anymore and the "exe.xml" file is located in "Microsoft Flight Simulator" folder:
![image](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/1161879/fab553f0-3530-487e-88a0-4dc6f474805e)

**Comment by hawkeye-stan** [comment]
Thanks for the screenshot and information. I've updated the code to look for exe.xml in "Microsoft Flight Simulator" folder instead. Hopefully it will work since I don't have Steam version of MSFS to test. Next release will be by end of July.

**Comment by hellobody** [comment]
Hey @hawkeye-stan.
I think that would be wrong fix.
Just remove LocalCache subfolder from path and it'll work.
I believe we need keep Steam version support.
Thank you.

**Comment by hawkeye-stan** [comment]
Yeah, I've removed "LocalCache" from the subfolder path so the path is just "\Microsoft Flight Simulator\".

**Comment by hellobody** [comment]
Ah, sorry. Got it.

**Comment by hawkeye-stan** [comment]
Version 4.1.1 has been released and hopefully it fixes this issue.

**Comment by hellobody** [comment]
Great. Thank you.
