### ISSUE TITLE
CommandLine tags are lost in EXE.XML when modified by popout-panel-manager

### ISSUE THREAD

**Issue by mdenadal** [hawkeye-stan/msfs-popout-panel-manager#121]
Enabling or disabling autostart on MSFS loading obviously modifies EXE.XML
If existing EXE.XML contains intems with CommandLine tag, the CommanLine tag get lost.

Example:
Before adding autostart
  
`<?xml version="1.0" encoding="utf-8"?>`
`<SimBase.Document Type="Launch" version="1,0">`
`  <Descr>Launch</Descr>`
`  <Filename>exe.xml</Filename>`
`  <Disabled>False</Disabled>`
`  <Launch.Addon>`
`    <Name>AutoHotKeyPauseButton</Name>`
`    <Disabled>False</Disabled>`
`    <Path>C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe</Path>`
`    <CommandLine>Z:\AutoHotKeyScripts\Controller_PTT_for_IVAO_Altitude.ahk</CommandLine>`
`  </Launch.Addon>`
`</SimBase.Document>`

after adding autostart:

`<?xml version="1.0" encoding="utf-8"?>`
`<SimBase.Document Type="Launch" version="1,0">`
`  <Descr>Launch</Descr>`
`  <Filename>exe.xml</Filename>`
`  <Disabled>False</Disabled>`
`  <Launch.Addon>`
`    <Name>AutoHotKeyPauseButton</Name>`
`    <Disabled>False</Disabled>`
`    <Path>C:\Program Files\AutoHotkey\v2\AutoHotkey64.exe</Path>`
`  </Launch.Addon>`
`  <Launch.Addon>`
`    <Name>MSFS Popout Panel Manager</Name>`
`    <Disabled>false</Disabled>`
`    <Path>Z:\Popout Panel Manager\MSFSPopoutPanelManager.exe</Path>`
`  </Launch.Addon>`
`</SimBase.Document>`

The CommandLine tag for AutoHotKeyPauseButton is get lost.

**Comment by hawkeye-stan** [comment]
Will be fixed in the next release by end of July.

**Comment by hawkeye-stan** [comment]
Version 4.1.1 has been released and hopefully it fixes this issue.

**Comment by mdenadal** [comment]
Thank you @hawkeye-stan ! I confirm 4.1.1 fixes the problem!
