### ISSUE TITLE
Views skip randomly during flight

### ISSUE THREAD

**Issue by ik1mdh** [hawkeye-stan/msfs-popout-panel-manager#122]
Good morning,
I would like to report a problem while using pop out manager.
My configuration is: Boeing 737-800 home cockpit, msfs 2020, operation with a single PC, 12 GByte graphics card, Windows 10, 9 monitors (4 with graphics card + 5 with external graphics cards).
My problem is the following: after I activated pop out manager without any warning and randomly the views lose their initial position and are repositioned randomly on the 9 monitors. By restarting the application they return to their initial position. This problem can happen 1 to 3 times in a flight.
Can you suggest me some solution??
Thank you in advance for the time you have dedicated to me.
Good day.
Andrea Buoso

**Comment by hawkeye-stan** [comment]
Not sure why POPM will move the panel unexpectedly. Couple years ago, there seems to be a bug in MSFS where panel will get refreshed by the game for no real reason and this refresh will cause panel to move to it's original pop out position (position MSFS thinks it should be). And this bug could be still happening but I haven't received any report about this issue for couple years now.

In any case, try to following. Turn on Panel tracking option in POPM preference/pop out settings option. This will lock panel in place and any mouse movement or some level OS movement will return the panel to the position that is set by POPM. Hopefully, this fix the issue. If not, you can close POPM after pop out has been completed if you're not using POPM touch emulation feature to make sure POPM moving panel unintentionally.

![image](https://github.com/user-attachments/assets/f4a03478-1e85-44b0-a90b-2c787496dfa4)

**Comment by ik1mdh** [comment]
Good morning,
In the meantime, thank you for taking the time to answer my problem. I will
try to use your advice and then do some test flights. Once the test flights
are finished I will send you my results.
Good day.
Andrea Buoso

Il giorno ven 26 lug 2024 alle ore 15:35 Stanley ***@***.***>
ha scritto:
