### ISSUE TITLE
Can't access program after Min to tray is enabled. 

### ISSUE THREAD

**Issue by drumdaddy39** [hawkeye-stan/msfs-popout-panel-manager#132]
I need help. 
I clicked start the application in minimized mode in system tray. I did this after only setting up my PFD to see how it will work. Now I want to set up my MFD but the program is locked  in the system tray and I can't get back to the screen where you target more screens. Is there a shortcut key to get you back to the settings menu so I can uncheck that preference. I can't find it in the documentation.

This may just be user error.

**Comment by RaduRS** [comment]
I have exactly the same problem. I can only right click the icon so I get: 'Start Pop Out', Profiles and Exit. Also if I double click on it from the tray it will close the app. I there a way to revert that minimize to tray action?

**Comment by drumdaddy39** [comment]
Mine responds the exact same way.

**Comment by drumdaddy39** [comment]
This issue is fixed. Download the latest version and it will give you an open option to click on after it is minimized to the tray.
