### ISSUE TITLE
Feature request: Configure which custom camera is used for auto panning camera

### ISSUE THREAD

**Issue by joeherwig** [hawkeye-stan/msfs-popout-panel-manager#15]
Dear Stanley, 

As i'm using in all my planes [Alt]+[0] for a outside view without VC (in front of VC) and [Alt]+[1] as standard VC PIC view, it would be great, if it would be an option to set the number of the custom camera to be saved for the auto panning camera.
Of course both views are assigned to joystick buttons as well.

To use the tool in my setup it would require that i have to edit the cameras.cfg for all planes, remove the custom camera 0 and reassign the joystick button for all planes.

Probably i'm not the only one and if the effort for selecting the custom camera it would be really helpful.
It not, please let me know, so that i can completely rework my setup to get your great tool available. :-)

Best regards,

         Joe

**Comment by hawkeye-stan** [comment]
I'll be adding option to configure auto panning view to use Alt-0 through Alt-9. The next version of the app v3.3 should be out before the end of April.

**Comment by hawkeye-stan** [comment]
Feature added in version 3.3 release.
