### ISSUE TITLE
Improvement Request: bind aircraft instead of Livery

### ISSUE THREAD

**Issue by joeherwig** [hawkeye-stan/msfs-popout-panel-manager#16]
As the instruments and their placement depends on the model (aircraft) and not the livery I strongly suggest to refer to the aircraft type instead of the Livery. It makes it ways easier to just fly with new liveries as long as the model underneath is the same. 

That would be great for people flying differet liveries. 

See [similar thread for FSUIPC](https://forum.simflight.com/topic/93496-for-every-liverie-a-new-profile/) .

**Comment by hawkeye-stan** [comment]
I'm getting plane model info from SimConnect variable and currently the only info I get is a unique livery name for each plane model. I've to investigate how FSUIPC binds to aircraft.cfg file and see if I can incorporate it into Pop Out Manager.

One improvement I can think of is for Pop Out Manager to allow binding of a profile to more than one livery which will temporary solve the problem. This maybe a stop gap before I attempt to rewrite how the entire profile binding works within the app.

**Comment by hawkeye-stan** [comment]
Improvement to bind multiple liveries to a profile added in version 3.3 release. I still need to investigate aircraft files and all the in and outs such as encrypted files, etc. With multiple aircraft liveries support in current version, this almost solve thus particular problem for now.

**Comment by hawkeye-stan** [comment]
Target for release v3.4.2

**Comment by hawkeye-stan** [comment]
Implemented in release v3.4.2
