### ISSUE TITLE
PMDG 737?

### ISSUE THREAD

**Issue by demariners** [hawkeye-stan/msfs-popout-panel-manager#24]
Does this work on the PMDG 737?  It does not appear so.  

Thanks

**Comment by hawkeye-stan** [comment]
Yes, it does work on PMDG 737. You will need latest update of the plane from couple weeks ago when it added pop out functionality for panels.

**Comment by hawkeye-stan** [comment]
It should work with PMDG 737 with no special configuration needed (no power on for cold start needed).
