### ISSUE TITLE
Touch functionality not working in SU10 Beta v1.27.13.0

### ISSUE THREAD

**Issue by Latka808** [hawkeye-stan/msfs-popout-panel-manager#35]
I posted a video over in the MSFS forums but wanted to make sure folks could see it here too

https://forums.flightsimulator.com/t/msfs-pop-out-panel-manager-with-touch-support-v3-4-1/460613/356?u=latka

RealSimGear GTN750 with Jay Dee's 750 replacement for the GNS530 in the v2.0 (testing) version of the BN-2 Islander. Popout manager works and gets the GTN750 to the RSG device, which through the RSG Device Interface is recognizing the knobs and buttons, but not touch events. Short video here:  https://youtu.be/GC3Cr0owgR0

**Comment by hawkeye-stan** [comment]
Issue resolved. RSG GTN750 needs to be designated as touch device.
