### ISSUE TITLE
POPOUT 2 INSTRUMENTS TOGETHER ON HONDA JET - FAILED WHEN SCALING

### ISSUE THREAD

**Issue by fabianovm** [hawkeye-stan/msfs-popout-panel-manager#42]
Hello Stanley and friends! I´m trying to first create a profile to configure the 2 GTC´s - Garmin Touch controls on a Honda Jet, SU10, MSFS popout manager v3.4.3 and v3.4.2 also. No success. I experience same problems, when I select instrument 1 and 2, after that, click control+left mouse and for a few seconds I see both together in a msfs popout window but something happens, and i got the same error here reported "Unable to pop out panel #" and just one of the gtc stays on popped out windows. Tried to make it work for the whole night, no success, if you guys can help or need something from me in order to help, let me know! Oh, almost forgot, both of them are able to pop out using default msfs altgr+left mouse, so , they pops out, both.!

UPDATE1: If I select just one instrument GTC at a time it works perfect, selecting both of them it goes wrong in the moment the pop out window seens to make calculations. One instrument appears completely, the other in its side just the title window, but it is there. I thing when program automation tries to click on a button title of the not totally visible instrument, to make adjustments, something goes wrong and then the reported error message. I am in 4k, 60 hz, tried with and without vsync, overlays are positioned correctly, just tested. The issue is something in the process of resizing/calculating both instruments in the same popout window.

**Comment by fabianovm** [comment]
![hjet gtcs](https://user-images.githubusercontent.com/86928223/191967628-3f66f1eb-0fa7-42a5-8e46-74712c347ac8.png)

**Comment by fabianovm** [comment]
Stanley, here is a video of the full process that shows the issue when popout both gtc´s at same time. Sorry i made it on my phone but it is possible to see what is happening, thanks!!!
https://drive.google.com/file/d/1JzrTrZrnzStytaZEr8wuRo8CjGfubSj8/view?usp=sharing

**Comment by hawkeye-stan** [comment]
Hi fabianovm,

Thanks for the info and the video. This really helps me to confirm panel scaling in MSFS when popping out two panels with very different width is causing the mouse cursor to click at the wrong place when separating them. This is definitely the same issue from #40. I will have to redesign the algorithm regarding panel's title bar magnifying glass icon location calculation. This issue also mostly affects 4K or high resolution monitor. I will shoot for a test build to resolve this problem sometime this weekend.

I'm merging this issue with #40. Please track that issue instead and stay tune for a custom test beta build this weekend for you to test. 

Stanley

**Comment by fabianovm** [comment]
Hi Stanley, happy to hear from you that I helped in anyway and most important, it is the same issue in #40 and you will be looking to it with care. No words to say, just thank you, if you need something let me know. I will follow #40 from now and as soon a new beta is posted I test and let you know. Regards!!
Fabiano

**Comment by hawkeye-stan** [comment]
Merge to #40
