### ISSUE TITLE
Feature request: Add option to pause simulator while panels are popped out

### ISSUE THREAD

**Issue by kPanesar** [hawkeye-stan/msfs-popout-panel-manager#43]
When doing landing challenges, for example, it's difficult to follow course while the panels are popped out. It would be great to add an option automatically do an active pause and unpause while the panels are popped out.

**Comment by hawkeye-stan** [comment]
I will look into the feasibility of this feature and try to add it to next release of the app.

Stanley

**Comment by hawkeye-stan** [comment]
I will investigate and will try to add this feature in next version of POPM.

**Comment by hawkeye-stan** [comment]
Updated targeted to release for v4

**Comment by hawkeye-stan** [comment]
Released in version 4.0
