### ISSUE TITLE
Popout manager %userprofile%\Documents\MSFS Pop Out Manager folder/files not created

### ISSUE THREAD

**Issue by Gascrich** [hawkeye-stan/msfs-popout-panel-manager#46]
Hi,
Thank you for this excellent product. I was able to create my 530 and 430 pop-out panels on a second monitor, but when I quit the application or MSFS simulator, every thing is lost.
Also, the folder "%userprofile%\Documents\MSFS Pop Out Manager" is not created. I understand that %userprofile% is my "C:\users\my_folder\Documents\"

I have version 3.4.5
MSFS is up-to-date, both sim and world
I use Steam edition of MSFS, and it is installed on a SSD drive, different than C:
I use the application as administrator.
I installed MSFS pop out on the same drive, and made sure that the folders "mobiflight-event-module" and "zzz-ready-to-fly-button-skipper" are in the Community folder.
I made sure I have the VC++ redistributable 2015-2022 x64 installed.
I do not receive any error messages when using MSFS pop out Manager.
Any change on the Preferences are not retained after closing the application.

I hope I have given sufficient information.

Thank you in advance for your support.

Richard

**Comment by hawkeye-stan** [comment]
*** reposting reply from Flightsime.com***

Hi Richard,

The profile setting folder should be inside your Windows login account folder. So “%userprofile%\Documents\MSFS Pop Out Manager” should be “C:\users\XXXX\Documents\MSFS Pop Out Manager” where XXXX is your user login account id. If the folder cannot be created, then it looks like something in your system is preventing the creation of this folder such as antivirus software.

Would you please try creating the above folder manually? Once it has been created, start Pop out manager. You should immediately see a file “appsettingdata.json” gets created. If it does, then everything should be OK. If not, then there is something restricting read/write access to your Documents folder.

**Comment by hawkeye-stan** [comment]
*** reposting reply from Richard *** (thank you Richard for finding the solution to issue)
 
It was an issue with Windows security blocking write access to user folder.
