### ISSUE TITLE
json indent

### ISSUE THREAD

**Issue by Narvik-Ramius** [hawkeye-stan/msfs-popout-panel-manager#47]
Hi !
Just a little suggestion here ...
When you have to fine-tweaking popped out instruments size and position, it's more precise to directly edit the .json file and made adjustments pixel by pixel.

To make the process easier, could it please be possible to auto-indent the userprofiledata.json file ?

What I'm doing currently is :
- opening userprofiledata.json file with notepad++
- copy/past json content in https://json-indent.com/
- paste / replace result into notepad++
- save file
- restart msfs popout panel manager

**Comment by hawkeye-stan** [comment]
You can download visual studio code (free) and open the json file in the editor directly. Then right click the editor screen and format document. This will indent the json file for you. After that just save the json file. You don't need to open and paste the file back and forth between notepad and online json editor.

Stanley
