### ISSUE TITLE
touch screen registers as "double click" in asobo longitude.

### ISSUE THREAD

**Issue by jbud** [hawkeye-stan/msfs-popout-panel-manager#48]
When I use an external display and I use popout manager on the TSC in the g5000 longitude it registers every tap twice if I tap flight plan it taps the same area twice registering flight plan -> add waypoint. 

Popout manager settings: full screen, touch enabled

Windows 11, MSFS SU11

this happens on two different external display types: Generic 7 inch touch screen, wireless display via spacedesk

![](https://user-images.githubusercontent.com/6253799/204412430-d3563a50-3c25-44bb-bb5b-2b4f758631cc.jpg)

**Comment by jbud** [comment]
https://user-images.githubusercontent.com/6253799/204416035-8ba989b9-1fd2-43df-8301-98ff4c1b367d.mov

example of what I'm experiencing

**Comment by jbud** [comment]
Seems I was able to workaround this by editing the source code in WindowsAgent\\TouchEventManager.cs:148

It seems like every touch event on my system hooks \_isDragged and is causing a double click event. 

```c#
//InputEmulationManager.LeftClickFast(info.pt.X, info.pt.Y);
```

**Comment by hawkeye-stan** [comment]
I haven't had any users reporting issue with touch emulation registering as double click. In my code, the first click was to emulate focus of the pop out window and set the potential drag coordinate (if needed), and the 2nd click is actually emulated click of the window. For some reason in your setup, click focus is not needed! 

Anyway, it's awesome you were able to resolve the issue by updating the code.

**Comment by hawkeye-stan** [comment]
Pull requested will be reviewed and investigated regarding "_isDragged" systems hooks issue. Thank you jbud:)
