### ISSUE TITLE
App has to be on the main monitor to work

### ISSUE THREAD

**Issue by hawkeye-stan** [hawkeye-stan/msfs-popout-panel-manager#5]
Reported by RMROC451,

I’ve noticed, when displaying MSFS on my 4k monitor (mixed with other 1920x1200 monitors), I’ve had to make sure the program is on the same monitor as my 4k monitor, or it won’t get the click positions right.

Unsure if that is a bug, or if that is just something wonky with my profile/setup.

**Comment by hawkeye-stan** [comment]
Unable to reproduce the issue from my monitor setup. Need to look deeper into cursor click timing for multiple hi resolution monitor or Windows coordinate calculation with multi monitor setup.

**Comment by rmroc451** [comment]
4k monitor is not primary.  4k monitor runs msfs though in windowed mode.

I have them setup like this:

[ 4k ][1200p][1200p]
[1080p]

The 1080p my primary, it runs my airmanager panels.

If I run the app from the 1200p monitor to the right of the 4k monitor, it fails to pop out, even if I manually line up the indicators on the instruments (c172 gns 530, gns 330, auto pilot)

**Comment by hawkeye-stan** [comment]
Hi rmroc451,
 
I've done a test and try to emulate your monitor configuration and make my 1080p as the primary monitor.

[4K][1440P uw]
[1080p]

From the attached screenshot, the 1080p monitor (label #2) is my primary and pop out manager ran on that screen. So when I clicked "start pop out", the mouse will move up to the 4K monitor and pop out the panels. The panels will appear in the upper left corner of the 1080p monitor. Are you getting the same thing? I tested using C172 PFD and MFD panel.

The coordinates recorded in pop out manager is a little funky though. Since coordinate (0, 0) is the upper left corner of the 1080p monitor, the 2 panels have coordinates of (1400, -260), (1800, -260). I also move the pop out manager to the 1440p screen which is to the right of 4K and I was able to pop out the panel. I also tested with full screen and window mode.

It will be super helpful if you can share a screenshot of your monitor configuration from Windows System->Display settings (similar to the attached screenshot). Also, a screenshot of the resulted coordinates for all the panels of your profile your created from pop out manager. I can then do an analysis and see what is off. I greatly appreciated your help and I'll continue investigating the issue. 

Btw, are you using version 3.0 of the app?

Thanks, 
Stanley

![monitorconfig](https://user-images.githubusercontent.com/72271266/148168825-b17f5b07-e3f9-4425-83c4-c3b2107889db.png)

**Comment by rmroc451** [comment]
> Hi rmroc451,
>  
> I've done a test and try to emulate your monitor configuration and make my 1080p as the primary monitor.
> 
> [4K][1440P uw]
> [1080p]
> 
> From the attached screenshot, the 1080p monitor (label #2) is my primary and pop out manager ran on that screen. So when I clicked "start pop out", the mouse will move up to the 4K monitor and pop out the panels. The panels will appear in the upper left corner of the 1080p monitor. Are you getting the same thing? I tested using C172 PFD and MFD panel.
> 
> The coordinates recorded in pop out manager is a little funky though. Since coordinate (0, 0) is the upper left corner of the 1080p monitor, the 2 panels have coordinates of (1400, -260), (1800, -260). I also move the pop out manager to the 1440p screen which is to the right of 4K and I was able to pop out the panel. I also tested with full screen and window mode.
> 
> It will be super helpful if you can share a screenshot of your monitor configuration from Windows System->Display settings (similar to the attached screenshot). Also, a screenshot of the resulted coordinates for all the panels of your profile your created from pop out manager. I can then do an analysis and see what is off. I greatly appreciated your help and I'll continue investigating the issue. 
> 
> Btw, are you using version 3.0 of the app?
> 
> Thanks, 
> Stanley
> 
> ![monitorconfig](https://user-images.githubusercontent.com/72271266/148168825-b17f5b07-e3f9-4425-83c4-c3b2107889db.png)
> 
> 

I am using 3.0.  Wasn't running this app from 1080p, but the side monitor.

When I do run it from the 4k, the pop outs do open on the upper left of the 1080p monitor like yours do.

Can you try running from your right most monitor?

**Comment by rmroc451** [comment]
@hawkeye-stan Here is a screenshot of all my monitors, how they are laid out and what they display during a sim session.
![desktop](https://user-images.githubusercontent.com/15070945/148275621-1e38e82e-7888-4d3f-bb6c-3817957a43d7.jpg)

**Comment by hawkeye-stan** [comment]
@rmroc451 Thanks for all the info. I'll get started on the investigation.

**Comment by hawkeye-stan** [comment]
@rmroc451 

I think I come up with the result of the monitor investigation. It probably has to do with Windows version and how Windows API reports monitor coordinates. Unfortunately, since I developed my app on Windows 11 and don't have MSFS on a Windows 10 machine to test, I'm guessing Windows 10 treated monitor configuration differently behind the scene. This funky coordinate problem may have gotten fixed in Windows 11.

![monitor-investigation](https://user-images.githubusercontent.com/72271266/148335824-8dae5385-6039-4b43-a369-4d8a2771afbd.png)

To reproduce the 3 panels coordinates result similar for your steam gauge C172 (your gauges are little bit to the right of center and at lower half of your 4K screen), I've to arrange monitors in the configuration as shown in the screenshot above. The screenshot actually makes sense for Windows 10 and how it reported screen coordinates as they are. In the screenshot:

Monitor #3  (4K screen = your 4K screen)
Monitor #1 (1200p = 1200P on your right side)  - but this get squeeze in between two monitors 
Monitor #2 (primary 1080p = your air manager monitor) - it tries to center across your top 3 monitors

I think in Windows 10 when a monitor is straddled between 2 monitors from height perspective and to the side, it does not know how to handle it and it squeezes the monitor in between the top and bottom monitor in coordinate calculation. So, monitors line up from top to bottom in a straight line in coordinates perspective even though in your windows settings, it appear differently as how you see your monitors. So your monitors setup in coordinate system is probably like the screenshot below if it is using Windows 11 coordinate system.

![monitor-probable](https://user-images.githubusercontent.com/72271266/148339590-f6cd2279-1a92-4fc2-abc0-dd947b8cb568.png)

And I guess as you move pop out manager around, it changes the starting point in how coordinates are calculated and that's probably why the app only works in certain way.

Really sorry the answer is a little bit technical and currently I probably won't be able to fix your issue. There may not be a solution that will work for both OS but I'll continue to search for answer and if I find it, I'll code in into the next release. You may not be the only one that has multiple monitors that is on Windows 10 with the issue since 90% of users are still on Windows 10. And unfortunately, I'm on Windows 11 (trail blazing) and I can tell you the OS sucks. I wanted to rollback but it is too much work to do it right now, LOL!

Once again, really thank you for your patience and all your help,
Stanley

**Comment by rmroc451** [comment]
Hey, I'm a dev too, so I appreciate the technical answer!

I've been putting off 11 on my gaming rig, and if I update it in the near future, I'll let you know the results of trying this again there.

**Comment by hawkeye-stan** [comment]
Please try out Version 3.2 beta and report back if it fixes your issue. I've added mixed monitors resolution and scaling support and it may fix the issue you're reporting.
