### ISSUE TITLE
After auto-popout, Right Alt is stuck

### ISSUE THREAD

**Issue by jopeek** [hawkeye-stan/msfs-popout-panel-manager#58]
I always have to press the right alt key once after the auto popout is finished or else it remains held and if I click on a display, MSFS will pop it out.

**Comment by hawkeye-stan** [comment]
I will investigate your issue about stuck right alt-key. Unfortunately, I'm unable to reproduce your issue and I don't have other users reporting this particular. 

There could be a work around. You can bind another keystroke to pop out panels in MSFS. First, go into MSFS control options and in keyboard binding, search for "Miscellaneous => New UI Window Mode". Bind Ctrl + Right Ctrl as secondary keystroke. You don't have to delete or overwrite the default "Right Alt". Next, in POPM, go to File => Preferences => Pop Out Settings, scroll to the bottom and check "use Left Control + Right Control to Pop Out Panel". This will use the new keystroke binding for MSFS to perform the pop out. Hope this gets around your stuck Right-Alt key issue.

**Comment by jopeek** [comment]
I might try that, thanks. I’m also happy to live with it if it’s a unique issue to me. Not a big deal.

**Comment by domineum** [comment]
Just discovered the same issue. One press on right alt usually solves it. Tried two different keyboards already.
