### ISSUE TITLE
AAU 1 TBM 930 GTC 580 Instrument Panel Touch not working

### ISSUE THREAD

**Issue by rockywaves** [hawkeye-stan/msfs-popout-panel-manager#60]
I upgraded to the AAU 1 release today so I could get the TBM 930 enhancements working.  I am unable to get the touch function to work on the GTC 580 instrument panel using POM.  I have "touch enabled" for the instrument panel.  The AM GTC 580 touch buttons works fine.   The touch function on the GTC 580 instrument panel is erratic....touch is recognized less often than not.  Not sure what to do to test it further.

**Comment by rockywaves** [comment]
Update after more testing of the problem:  If I enable full screen mode, then the touch works on the GTC 580 instrument panel.  I have tried enlarging the instrument panel to different sizes, but touch does not work consistently.    I stopped running Air Manager while testing, to rule it our as part of the problem.

**Comment by hawkeye-stan** [comment]
I don't have AAU1 install yet. Once I get it install, I'll try to reproduce your issue on TBM 930 and hopefully I can find a fix.

**Comment by rockywaves** [comment]
Thank you, I appreciate your looking into it and await your response.

**Comment by hawkeye-stan** [comment]
I'm able to test the latest AAU1 update and TBM 930 touch screen (the one in the lower half half the the instrumentation cluster) is indeed more erratic and much less responsive than before. One out of four times, I need to touch a button twice to click it. I've an USB monitor connected directly to my video card (not using Spacedesk) so the latency should be minimal. It looks like the AAU1 code is less performant than before the update. I think I'm able to get the responsiveness back by setting the following:

In POPM, go to setting menu File -> Preferences -> Touch Settings. Increase the "Refocus Game Window" to at or above 1000ms (1 second). What this does is after you touch TBM pop out panel, POPM will try to return the mouse cursor to MSFS so you can get your flight control back. I believe anything lower than 1 second is causing a performance conflict within MSFS code. 

If this does not work, please play around with the next setting "Touch Down Touch Up Delay". Setting this to 25ms may increase the response of touch.

Stanley

**Comment by rockywaves** [comment]
Stanley, thank you and I will do as you have suggested.  Do you know why
full screen works fine,  but any other size screen behaves as you
described?  Did full screen work fine for you?   Is there a way to report
this behavior to the AAU 1 dev team?

Bob
