### ISSUE TITLE
MSFS2020 CTD if try going back to globe

### ISSUE THREAD

**Issue by Blizzard225** [hawkeye-stan/msfs-popout-panel-manager#61]
Hello,

I use MSFS2020 Pop Out Panel Manager version 3.4.5.
If the application is with MSFS2020 (PMDG B738) running and all Pop Out Windows are placed and saved all worked fine. But, if I'll finish MSFS2020 or I would like to go back to the globe page of MSFS then MSFS crashed all the time. That happend if I finish Pop Out Manger first and then MSFS, too.

You can see the error.log and programs VC++ in the attachment.
Best regards Rolf
[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/10610786/error.log)
![Programs ](https://user-images.githubusercontent.com/56797126/216815614-50a9a268-3202-48a5-a347-e6eb7f56f1a3.png)

**Comment by hawkeye-stan** [comment]
Looks like something in your system is causing SimConnect (part of MSFS SDK) to crash. SimConnect is needed so Pop Out Panel Manager can detect when a flight has been started or ended. Could there be other plugin in your system that could be conflicting with SimConnect?

**Comment by Blizzard225** [comment]
Thank you for reply. I use a lot of Tools/Apps during my flights, therefore it's quite possible that'll be a conflict. Do you know if there are a list/summery of applications which use SimConnect with MSFS? I appreciate every help! Regards Rolf

**Comment by Blizzard225** [comment]
I tried the Pop Out Panel Manager without any other applications/Tools and if the MSFS is loaded completely and then I finish POPM first or MSFS2020 in order to go back to globe of MSFS then MSFS crashes to Desktop, too.
