### ISSUE TITLE
Confusion... why 2 installers?

### ISSUE THREAD

**Issue by winternet-studio** [hawkeye-stan/msfs-popout-panel-manager#63]
In the latest release there are two installers:

- msfs-popout-panel-manager-cj4-beta-bug-fix.zip
- msfs-popout-panel-manager.zip

But no guide whatsoever as to why one would choose one over the other! If the first contains a bugfix why wouldn't I always want to use that one?

**Comment by hawkeye-stan** [comment]
The extra cj4 beta installer has been removed.
