### ISSUE TITLE
Cannot resize popped out window.

### ISSUE THREAD

**Issue by Jacktherookie** [hawkeye-stan/msfs-popout-panel-manager#66]
Hi, I'm currently trying to pop out G1000 Screen.
When I pop out G1000, I cannot change actual ratio of G1000 although I change width.
I do have 2 dedicated display for G1000(1440*900). Is there any way I can change ratio?

**Comment by Jacktherookie** [comment]
![Uploading 20230313_202120.jpg…]()

**Comment by Jacktherookie** [comment]
![20230313_202120](https://user-images.githubusercontent.com/39476173/224689167-ba2c63b3-9179-49af-8eee-3d851f61bcc2.jpg)

**Comment by Jacktherookie** [comment]
Those black part of the screen. I cannot remove it.. Any help?

**Comment by Jacktherookie** [comment]
> The size of G1000 pop outs are coded as part of G1000 design and POPM will not be able to control it. I believe the G1000 ratio in game is 1024x768 (ratio 1.33) and your screen is 1440x900 (ratio 1.6). The black bars are there because the ratios are different. You've to edit g1000 panel configuration files to change the ratio to fit your screen.
> 
> Currently, I'm on vacation and won't be back home to access the game until next week. If you've installed your game through Steam of have installed MSFS to a separate directory for game pass/MS store version of the game, you should have access to the G1000 panel configuration files. I'll send instruction in how to edit the files when I get home from vacation next week.
> 
> Stanley

It's quite odd that MSFS does not natively support resize of popped out screen. Anyway, Really appreciated for your reply, and I'll be waiting for your kind help!

**Comment by carlosdesedas** [comment]
> > The size of G1000 pop outs are coded as part of G1000 design and POPM will not be able to control it. I believe the G1000 ratio in game is 1024x768 (ratio 1.33) and your screen is 1440x900 (ratio 1.6). The black bars are there because the ratios are different. You've to edit g1000 panel configuration files to change the ratio to fit your screen.
> > Currently, I'm on vacation and won't be back home to access the game until next week. If you've installed your game through Steam of have installed MSFS to a separate directory for game pass/MS store version of the game, you should have access to the G1000 panel configuration files. I'll send instruction in how to edit the files when I get home from vacation next week.
> > Stanley
> 
> It's quite odd that MSFS does not natively support resize of popped out screen. Anyway, Really appreciated for your reply, and I'll be waiting for your kind help!

I have exactly the same problem.  I own two Flightsimbuilder G1000 displays, both which have a 1024x768 resolution and when I enter Full Screen, I get the same black bars to the sides as the first image on this post.  I don't remember exactly but the width and height showing in the MSPopoutmanager screen is an odd one, like 1023x733 or something in that sense.  I cannot get them full screen to 1024x768.  Thanks!

**Comment by hawkeye-stan** [comment]
I'm not even sure how Asobo/MSFS set the full screen aspect ratio when pop out enters full screen mode (using Alt-Enter keystroke). It may not even follow the default designed G1000 1024x768 aspect ratio. The only way to get around it is to use non-fullscreen mode and resize the pop out to fit your display resolution. I'll investigate and see if I can figure out how Asobo configure full screen display for instrumentation panels.

Stanley

**Comment by carlosdesedas** [comment]
yeap.. I think you're right, because I close the MSPoutManager app and try again to go fullscreen and got the same sidebars.  I think I didn't get them before SU12..  The problem is that if I "window" the popout screens, I still get the windows taskbars on both the PFD and MFD monitors.  and I don't want to disable/hide the taskbars on the Windows settings itself because then ALL the taskbars on additional monitors get disabled/hidden, and I need them on my secondary monitor where I use LittleNavMap, browsers, spad.next, etc.  

I hope my explanation makes sense.. LOL

**Comment by hawkeye-stan** [comment]
I think Asobo definitely changed their implementation in Su12 that is causing this new sidebar issue. And most likely G1000 may not be the only aircraft that has this problem. I bet I'll start receiving more report from other users asking for fix. I'll keep you up-to-date in what I learn from my investigation regarding this issue.

**Comment by Jacktherookie** [comment]
> I think Asobo definitely changed their implementation in Su12 that is causing this new sidebar issue. And most likely G1000 may not be the only aircraft that has this problem. I bet I'll start receiving more report from other users asking for fix. I'll keep you up-to-date in what I learn from my investigation regarding this issue.

I found that this started to happen since SU9.
Here's the link : https://forums.flightsimulator.com/t/pop-outs-should-respect-aspect-ratio-of-their-window/544711
