### ISSUE TITLE
Pop pouts duplicating same popout

### ISSUE THREAD

**Issue by mppearce2013** [hawkeye-stan/msfs-popout-panel-manager#67]
HI, hope your well. I have a weird issue which started for no apparent reason. No driver changes, only a windows 11 patch. The pop outs work fine, 
Poput 1 is good, popout 2 is good, then 3,4,5,6,7 are duplicates of pop out 2... Its the airbus a320 neo altimeter and nav screen. its really weird and just started happening I tried 3.4.6 as a test and same thing. I updated NVidia driver to 531.29 as a test same thing.

**Comment by hawkeye-stan** [comment]
This is an issue in the game and happens from time to time. No clue what is the actual cause and not aircraft specific. Usually restarting the game will fix the issue.
