### ISSUE TITLE
SU12 broke Popout Manager

### ISSUE THREAD

**Issue by JaimeLeon2** [hawkeye-stan/msfs-popout-panel-manager#68]
New MSFS2020 SU12 update out today and now msfs popout manager is not working.
Will give an error every time saying it cannot popout the windows.

**Comment by Delta-Charlie-DEV** [comment]
I confirm !

**Comment by hawkeye-stan** [comment]
Version 3.4.6.0321 should be compatible with Su12

**Comment by JaimeLeon2** [comment]
> Version 3.4.6.0321 should be compatible with Su12

Thanks Stan

**Comment by ricalv1973** [comment]
I confirm Version 3.4.6.0321, not working, won´t popout the windows after update to SU12

**Comment by hawkeye-stan** [comment]
Latest POPM should be working with SU12, please see my comment from other post that could be causing your issue.

https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/69
