### ISSUE TITLE
Some of the windows won't pop out after last update

### ISSUE THREAD

**Issue by dcohenb** [hawkeye-stan/msfs-popout-panel-manager#69]
I'm pretty sure this has nothing to do with the popout panel manager but i'm trying to confirm i'm not the only one

it seems pop out for screens (g1000 for example) stopped working, other simpler views (like radio frequency lcd panels) do work

is anyone else experiencing this?

**Comment by hawkeye-stan** [comment]
Sorry for the late reply. I just got the time to get back to MSFS after my time off. I've just experienced similar issue from starting a C172 flight even without pop out manager. The PFD popped out correctly but MFD did not. In reality, the screen that didn't get popped out was in effect totally off screen (probably MSFS SU12 messed up the location of the pop out). 

To fix this, when you use POPM, just run through the process for G1000 (or any other plane if it happens to them), you will see some screen get pop out but some do not. Now go to POPM configuration screen and find the pop outs that have off screen coordinates and move them to X:0 and Y:0, this will put them at the upper left corner of your main monitor. You can then just move them back to where they're supposed to be. 

I've no clue how updated SU12 feature saves the pop out locations and how to fix or clear them if they become corrupted. I need to do some investigation. But by using POPM, you can always override the wrong coordinates if they got messed up by SU12.

Stanley

**Comment by hawkeye-stan** [comment]
https://github.com/hawkeye-stan/msfs-popout-panel-manager/issues/73
