### ISSUE TITLE
(MSFS issue but making pop manager unusable) Instruments pop out full screen

### ISSUE THREAD

**Issue by theersink** [hawkeye-stan/msfs-popout-panel-manager#74]
Came back to the sim and now when I pop out a panel it is almost full screen and pop out manager can't pop the rest of the panels because it is in the way.

Screenshot attached but a simple solution (maybe, I am not a coder) would be to resize/position each panel before popping out the next? 

I see others with similar issue in the MSFS forums. I've tried positioning and then exiting but on next flight right back to full screeen pop outs, I think the internal saving does not work with 3rd party or something.

Anyhow, I thought I'd at least suggest/notify of this. Feel free to close if it is not possible.

Thank you for the awesome program.
![Screenshot 2023-04-29 214005](https://user-images.githubusercontent.com/70825153/235333165-4ca93b6f-fba3-44ba-977b-2d022b4b1db2.png)

**Comment by hawkeye-stan** [comment]
POPM only applies pop out resize once MSFS internal saving/loading feature does its thing after instrumentation panels are initially popped out. I'm not able to control the timing when this happens after each panel pops out in sequence. If POPM interfere this process too early, MSFS internal loading will override POPM. Unfortunately, SU12 made the pop out process worst and it is unreliable :(

I'll do investigation and see if I can figure out a reliable way to always override MSFS internal pop out resize and additionally without losing the ability to keep the correct pop out aspect ratio. For example:

1. Pop out the panel with number circle
2. Wait and look for the panel that actually got pop out on screen
3. If panel is found, resize it to 25% size (maintain aspect ratio) and move it to the upper left corner of the screen so it does not block the cockpit
4. Repeat step 1 to 3 for the next panel

The hard part is to get the timing right and figure out when MSFS internal has completed the placement and resize of panel before POPM takes over. I wish I can turn off MSFS internal panel saving/loading feature so POPM does not have to do any work around.

Stanley
