### ISSUE TITLE
I'm using a small 600x1024 touch screen for gtn750. When I have used the touch screen, I then can't use anything on the yoke unless I move the mouse onto the cockpit screen, how can I fix this

### ISSUE THREAD

**Issue by jim375** [hawkeye-stan/msfs-popout-panel-manager#77]

**Comment by hawkeye-stan** [comment]
Are you using Pop Out Manager to pop out panel, enable touch support for this panel on your touch screen, and enable game refocus in Pop Out Manager’s preference setting? That’s the only way Pop Out Manager can overcome the long outstanding MSFS bug that clicking or hovering your mouse over pop outs will cause you to lose flight control.
