### ISSUE TITLE
Pop up manager will not launch

### ISSUE THREAD

**Issue by NAJF3** [hawkeye-stan/msfs-popout-panel-manager#79]
Pop up manager suddenly will not launch. It worked perfectly 3 days ago. The computer was idle until today. It will not launch today. 
[error.log](https://github.com/hawkeye-stan/msfs-popout-panel-manager/files/11803447/error.log)
I see no new entry for today in the error file. When I try to launch, either normally or as administrator, hour glass icon displays for about 1 second an disappears. The pop out window does not appear. This is a great app. This behavior is very frustrating. Please help.

**Comment by hawkeye-stan** [comment]
Please try deleting all the files in the following folder in your system. Go to File Manager and paste in the following folder path:

%userprofile%\AppData\Local\Temp\.net\MSFSPopoutPanelManager

The above folder contains the extracted Pop Out Manager application files. Deleting the folder above will remove all application files for Pop Out Manager (Your profiles are saved in a different folder in your document directory). 

I'm guessing maybe something got corrupted for Pop Out Manager. Your attached error.log is showing a DLL error that I've never seen before. After deleting everything in the above folder, please rerun Pop Out Manger executable and it will perform a fresh extract of the application and hopefully this will resolve your issue.

Stanley

**Comment by NAJF3** [comment]
Thanks for your suggestions. Unfortunately, that did not resolve the issue. I then shutdown the Windows virus protection. That fixed it. For some inexplicable reason, MS virus protection decided that the exe was a bad actor. Everything seems to work just fine. I will let you know if any further issues appear.
