### ISSUE TITLE
The window is not freely scaling but keeps aspect ratio

### ISSUE THREAD

**Issue by TheGermanUSA** [hawkeye-stan/msfs-popout-panel-manager#80]
When popping out the FMS screen on PMDG 737-800, I can position it, most of the time the "Hide title bar" works, but no matter how wide I make it, it will always pop back to the aspect ratio of the original popout - which does not fit the monitor.
Is there any way you can fix this?

**Comment by hawkeye-stan** [comment]
I also fly 737-800 most of the time and I'm not able to reproduce your issue. The FMC screen when popped out by POPM should return to the location and set to the panel size you specified. As for the inner display ratio for the screen (with black bars or not), it is controlled by MSFS and PMDG and it should re-adjust to an aspect ratio you set when you defined the size of the panel. 

If you just perform manual pop out (Right-Alt Left-click), then the panel is controlled by MSFS pop out memory feature which is buggy and the location and size is stored by MSFS somewhere in the cloud. Using POPM overrides MSFS memory and set the panel to the exact location and size you wanted.

**Comment by TheGermanUSA** [comment]
To replicate - what I do to get the windows to ignore the original aspect ratio, is drag it to the monitor I want the popout on, then press ALT+ENTER to get to full screen and then adjust in the pop out manager as needed. When restarting the sim, the windows pop out, but it does not seem to recall the ALT-ENTER maximization and the correct locations/sizes.

**Comment by hawkeye-stan** [comment]
Please try version 4.0 of the app. To have the panel pop out to full screen, just configure and move the panel to your desire and select Full Screen Mode option for that panel. Next time when you start the flight and activate POPM start pop out, POPM will first move the panel to the configured monitor and then simulate Alt-Enter keystroke to maximize the panel.
