### ISSUE TITLE
Freeze when dragging on touch screen

### ISSUE THREAD

**Issue by Vevonix** [hawkeye-stan/msfs-popout-panel-manager#82]
I use a windows laptop with a touchscreen connected via spacedesk to the sim computer. 
Sometimes when I scroll trough one of the virtual touchscreens (touch and drag) the whole application freezes and needs to be restarted.

I can't really replicate it when I try, but it happened multiple times now.

**Comment by hawkeye-stan** [comment]
I will look into your issue and try to reproduce it. I'm not able to replicate it either and have not receive report about the crash. One thing to try in the meantime is in POPM, lock the aircraft profile once it's been configured, then go to preferences => pop out settings -> Enable panel reset when profile is locked and disable this setting. This will disable some detection of mouse moments and could minimize the chance of POPM of crashing.

**Comment by Vevonix** [comment]
I'm not sure if this is the same Issue but after updating to 4.0.1.1 it got really worse. Touching the screen anywhere produces "clicks" on the same wrong spot. After a couple taps on the screen the whole game/computer freezes/lags and exiting POPM solves the issue. I downgraded back to 4.0.0 and it runs fine now.
Btw, great software and I love the v4 update so far.

**Comment by Vevonix** [comment]
Not sure if its the same issue but after update 4.0.1.1 it got worse. In some aircraft i can't use the popped out touchscreens at all or they are very laggy/sluggish. Clicking/touching repeatedly on the panels either crashes POPM or my computer/game freezes up.
Killing the POPM exe solves the freezes. 4.0.1.1 is completely unusable for me. Going back to 4.0.0 solves my issue.
This happened in the Cockspur C510 Mustang and the Cowansim H125 if that matters.

Btw, love the v4 so far. I like the new UI.

**Comment by hawkeye-stan** [comment]
Your issue is currently being investigated. Hotfix will be available real soon. Sorry for the inconvenience.

**Comment by hawkeye-stan** [comment]
Hotfix v4.0.1.2 has been released and hopefully it fixes your current issue.
