### ISSUE TITLE
Popout went off-screen. unable to reset

### ISSUE THREAD

**Issue by domineum** [hawkeye-stan/msfs-popout-panel-manager#83]
Unable to reset G1000 MFD popout as it somehow went off-screen. How to reset popout-positions?

**Comment by hawkeye-stan** [comment]
You will need POPM to fix this MSFS bug. 
1. Start a new flight and do not pop out the MFD.
2. Use POPM to create an aircraft profile and select MFD as a panel.
3. Now click Start Pop Out, the MFD will pop out offscreen if no error.
4. Set Top and Left of the panel to 0, this will move MFD to upper left corner of your main monitor.
5. Once the panel is moved and visible, do not close the panel.
6. Now, exit the flight and go back to MSFS main menu. This will force MSFS to save the MFD location to 0,0. You can then either manually pop out the MFD or use POPM in subsequent flight.

Currently, POPM is the only way to fix this MSFS bug without deleting/reseting your MSFS game profile.

Stanley
