### ISSUE TITLE
Touch no longer working in 4.0.1.1

### ISSUE THREAD

**Issue by leinhto** [hawkeye-stan/msfs-popout-panel-manager#84]
I can't get touch working anymore in the new version. It just sits there and it appears to have a significant lag or it freezes, not just the MSFS but my computer where left click no longer works.

I reverted to 4.0.0 and I am back to normal.

**Comment by hawkeye-stan** [comment]
Your issue is currently being investigated. Hotfix will be available real soon. Sorry for the inconvenience.

**Comment by leinhto** [comment]
@hawkeye-stan Works now. Thanks for the great turn around. You guys are awesome!!
