### ISSUE TITLE
FBW A32nx pop out Flypad

### ISSUE THREAD

**Issue by Rotorxdan** [hawkeye-stan/msfs-popout-panel-manager#86]
Hi everybody,

 I am running into a problem while popping out the FBW A320nx panels. PFD,ND and ECAM work just fine. But when it comes the Flypad I am not being able to do the same. The view I use for popping out the panels, covers the previous mentioned panels, but the Flypad does not show on screen. If I tilt the view slightly left, the pad shows but it always produces an error while starting the pop out process.
Any help is appreciated

Thanks, Daniel

**Comment by hawkeye-stan** [comment]
What you can do is to zoom out (using the mouse view) show all panels are visible on the screen at once (see my screenshot - using 4K screen). Also make sure your zoom setting in MSFS general options - camera is set to 50%. There is currently a bug that if the zoom setting is anything other than 50%, saving and loading of custom camera view (which POPM relies on) does not work correctly. 
![screenshot](https://github.com/hawkeye-stan/msfs-popout-panel-manager/assets/72271266/110da451-8418-4803-b20a-63d10a41d534)

**Comment by Rotorxdan** [comment]
Thanks for your response, will take a look in a bit. Daniel
________________________________
De: Stanley ***@***.***>
Enviado: 30 de julho de 2023 14:49
Para: hawkeye-stan/msfs-popout-panel-manager ***@***.***>
Cc: Rotorxdan ***@***.***>; Author ***@***.***>
Assunto: Re: [hawkeye-stan/msfs-popout-panel-manager] FBW A32nx pop out Flypad (Issue #86)


What you can do is to zoom out (using the mouse view) show all panels are visible on the screen at once (see my screenshot - using 4K screen). Also make sure your zoom setting in MSFS general options - camera is set to 50%. There is currently a bug that if the zoom setting is anything other than 50%, saving and loading of custom camera view (which POPM relies on) does not work correctly.
[screenshot]<https://user-images.githubusercontent.com/72271266/257055094-110da451-8418-4803-b20a-63d10a41d534.jpg>

**Comment by Rotorxdan** [comment]
All working!!! thank you. Daniel
________________________________
De: Stanley ***@***.***>
Enviado: 30 de julho de 2023 14:49
Para: hawkeye-stan/msfs-popout-panel-manager ***@***.***>
Cc: Rotorxdan ***@***.***>; Author ***@***.***>
Assunto: Re: [hawkeye-stan/msfs-popout-panel-manager] FBW A32nx pop out Flypad (Issue #86)


What you can do is to zoom out (using the mouse view) show all panels are visible on the screen at once (see my screenshot - using 4K screen). Also make sure your zoom setting in MSFS general options - camera is set to 50%. There is currently a bug that if the zoom setting is anything other than 50%, saving and loading of custom camera view (which POPM relies on) does not work correctly.
[screenshot]<https://user-images.githubusercontent.com/72271266/257055094-110da451-8418-4803-b20a-63d10a41d534.jpg>

**Comment by Rotorxdan** [comment]
Hi Stanley, over two years ago you helped me solve a problem with the EFB pop out in the Fenix. I still use your program in my home cockpit, but lately I have encountered a problem I can’t seem to solve. When I turn the brightness knobs for the PFD, ND or Ecam, changes are only visible in the virtual cockpit, not in the home cockpit ones. Could you please help me with that? I am using Msfs 2020 by the way.

Thanks in advance, Daniel
