### ISSUE TITLE
4.0.1.2 still freezing computer

### ISSUE THREAD

**Issue by biterope** [hawkeye-stan/msfs-popout-panel-manager#89]
Tried 4.0.1.2 (showing as 4.0.1.0002 in the app) version and its freezing computer. I have to Clt+Alt+Delete and go to task manager and kill the process then I can continue in the sim/air manager

**Comment by biterope** [comment]
I'll give it go. I did find a possible workaround. The freezing happens frequently when using the FFX vision jet and only one GTC touch (swapping between pfd/mfd/nav with the soft keys) If I use all three GTC in separate bezels/pop-outs, its much better. I only had one freeze it that may have been due to me switching between the modes in a single pop-out. I had no such issues back in 3.5

**Comment by Terrisc61077** [comment]
Im haveing the same exzact issue with my Cirrus vision Jet as biterope.  The application will freeze not enabling me to  touch and minipulate any of the perspective touch screens , for the left (pfd) center (mfd) and right (nav/radios). It happens to me when I an entering a flight plan, scrolling through my checklist & switching between  PFD, MFD & radios.  It also diables my left click from selecting a window unless I select somthing in MSFS.  I usually have to got to explorer in the task manager & end the process, then restart.  My previous version (3.4.6) of MSFSpop out manager didnt this at all.  This started when I updated with the new update of  4.2.0002 a few weeks ago. I love the new layout, but hate the fact that I cant fly my Vision Jet like I used to in the previous edition without any issues.

**Comment by hawkeye-stan** [comment]
I don’t have vision jet to test and won’t be able to find out what is causing POPM to freeze for this specific aircraft. If you would like POPM to work, please go back to previous 3.4.6 version and select skip update when you launch the old version of POPM.
