### ISSUE TITLE
Popout Fails due to Navigraph loading

### ISSUE THREAD

**Issue by ToddLorey** [hawkeye-stan/msfs-popout-panel-manager#90]
Hi,

I'm using the PMDG 737 and along with it also having POPM handle my ATC/Navigraph Charts popouts.  Turns out it needs a little more delay after starting the move to the custom view (auto panning camera angle) in order to give the Navigraph time to finish loading before the rest of the instruments (PFD, MFD, etc) get popped out.  

When first loading up a plane, I do use the delay to allow for the Click Fly to happen, but it seems there needs to be a separate delay after that to allow the view direction change time to do its thing.  

When it fails, I typically end up with my Navigraph Charts window in place of the first instrument to be popped out (i.e. the PFD location).  If the Navigraph has already loaded, the second running of pop-out works great!

Hope that makes sense.

**Comment by hawkeye-stan** [comment]
Hi Todd,

I can confirmed your issue you're having. You can try extending the delay to 10 seconds in POPM (Preferences => Auto pop out panel settings) and hopefully Navigraph/ATC have been loaded completely before POPM starts PFD pop out.

Also, you can try latest v4.0.2 Beta (4) [msfs-popout-panel-manager-beta-4.zip](https://github.com/hawkeye-stan/msfs-popout-panel-manager/releases/download/v4.0.2/msfs-popout-panel-manager-beta-4.zip). It has a better optimized pop out routine and much more accurate timing. You can even set delay to 0 seconds and pop out will still work.

Here is a video my PC using Navigraph/ATC + three 737 panels based on your scenario that the timing seems to work correctly.
[vimeo link](https://vimeo.com/855833561)

If none of the above solutions work, please report back and I'll investigate what could be causing your failure scenario. Unfortunately, I'm out on holiday/vacation starting tomorrow but will be back home the following week and will definitely look into your issue. Also, please re-download version 4.0.1.2 (official POPM release) so you're not on beta release if you do not want to. All your aircraft profiles are compatible across both versions.

Stanley

**Comment by ToddLorey** [comment]
Awesome!  Thanks Stanley.  I'll give both ideas a try.  Have a good vacation!!
