### ISSUE TITLE
pop out absent

### ISSUE THREAD

**Issue by bobluckybob** [hawkeye-stan/msfs-popout-panel-manager#92]
when I click on exe, the panel does  not appear anywhere on monitor. it does not show as an app in task manager.

**Comment by hawkeye-stan** [comment]
Check if there is any error in event viewer in Windows. The app may fail to run for various reason on your computer. Need more info to support your isssue.

**Comment by bobluckybob** [comment]
I restored to a point prior to downloadwhen I click MSFSPopoutPanelManager.exe, the circlar 'thinking thinkng ' icon shows for a few seconds. panel does not appear.I ran event viewer again this AM & got 2 window-krnel-event-tracing/Admin errors in the last hour. One ESENT application error. Another application error. 22 windows-moderndeployment-diagnostic-provider/managementService  errors. 1 eventlog system error. 1 service cntrol manager system error. 6 distributedCom system errror.Panel manager does not show in setup ad/remove apps, nor in task manager active apps.Also, yesterday, I did get the panel open & sucessfully went thru the example in the tutorial. I then wanted to change profile to C172 G1000, so I closed the panel. That's the last I saw of it.Also, I had previously had set up wireless monitors in which I had 'lost' PFD popout panel. I was hoping to find it with panel manager. Could panel manager somehow be open & dwelling somewhere where those tablet monitors were?Does any of the bove give any clues?thanks,bob

    On Saturday, September 9, 2023 at 11:56:14 PM EDT, Stanley ***@***.***> wrote:  
 
 


Check if there is any error in event viewer in Windows. The app may fail to run for various reason on your computer. Need more info to support your isssue.

**Comment by hawkeye-stan** [comment]
Hi Bobluckybob,

You're the first one who is unable to open POPM. I'm guessing something in your system is causing POPM to crash or hanging. The event viewer messages you described are not POPM related. If POPM is running, it should show up in Task Manager. Since you don't see it, this means POPM is not running (crashed). Also, POPM will not show up in add/remove program since it doesn't need to be installed.

So, there could be many reasons for POPM fail to open.

1. Antivirus is blocking the app
2. Firewall is blocking the app and either hanging or crashing the app (since POPM checks this particular website for any POPM updates "https://github.com/hawkeye-stan/msfs-popout-panel-manager")
3. Another app in your system is interfering with POPM
4. .NET framework issue since POPM uses the latest .NET 7.0 framework (extra install is not required since POPM has it built-in)

Lastly, if POPM has successfully opened and hidden in one of your wireless monitor and your wireless monitor no longer exist. You will have to use keyboard commands to move window back to your main monitor.
https://www.elevenforum.com/t/move-off-screen-window-back-on-screen-in-windows-11.10694/

Stanley

**Comment by bobluckybob** [comment]
Thanks Stanley, I appreciate your help. Tried anti virus, firewall, safe mode, disabled all other apps that I could restore to previous, all to no avail. Who said "life's what happens to you when you're making other plans". I'll just have to live without.Have a great day.-bob
    On Sunday, September 10, 2023 at 10:47:42 AM EDT, Stanley ***@***.***> wrote:  
 
 


Hi Bobluckybob,

You're the first one who is unable to open POPM. I'm guessing something in your system is causing POPM to crash or hanging. The event viewer messages you described are not POPM related. If POPM is running, it should show up in Task Manager. Since you don't see it, this means POPM is not running (crashed). Also, POPM will not show up in add/remove program since it doesn't need to be installed.

So, there could be many reasons for POPM fail to open.
   
   - Antivirus is blocking the app
   - Firewall is blocking the app and either hanging or crashing the app (since POPM checks this particular website for any POPM updates "https://github.com/hawkeye-stan/msfs-popout-panel-manager")
   - Another app in your system is interfering with POPM
   - .NET framework issue since POPM uses the latest .NET 7.0 framework (extra install is not required since POPM has it built-in)

Lastly, if POPM has successfully opened and hidden in one of your wireless monitor and your wireless monitor no longer exist. You will have to use keyboard commands to move window back to your main monitor.
https://www.elevenforum.com/t/move-off-screen-window-back-on-screen-in-windows-11.10694/

Stanley

**Comment by bobluckybob** [comment]
Solved. Clicked properties on the .exe, & ticked the 'unblock' box.-bob
    On Sunday, September 10, 2023 at 10:47:42 AM EDT, Stanley ***@***.***> wrote:  
 
 


Hi Bobluckybob,

You're the first one who is unable to open POPM. I'm guessing something in your system is causing POPM to crash or hanging. The event viewer messages you described are not POPM related. If POPM is running, it should show up in Task Manager. Since you don't see it, this means POPM is not running (crashed). Also, POPM will not show up in add/remove program since it doesn't need to be installed.

So, there could be many reasons for POPM fail to open.
   
   - Antivirus is blocking the app
   - Firewall is blocking the app and either hanging or crashing the app (since POPM checks this particular website for any POPM updates "https://github.com/hawkeye-stan/msfs-popout-panel-manager")
   - Another app in your system is interfering with POPM
   - .NET framework issue since POPM uses the latest .NET 7.0 framework (extra install is not required since POPM has it built-in)

Lastly, if POPM has successfully opened and hidden in one of your wireless monitor and your wireless monitor no longer exist. You will have to use keyboard commands to move window back to your main monitor.
https://www.elevenforum.com/t/move-off-screen-window-back-on-screen-in-windows-11.10694/

Stanley
